version: "3.8"

services:
  # MySQL Database Service
  mysql:
    image: giahuy1412/mysql
    container_name: mysql-docker
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: login
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Backend Service (Spring Boot)
  backend:
    image: giahuy1412/backend:v1.9.4  # Thay vì build, sử dụng image đã push
    container_name: bsecurity_v.1.9.2
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  # Frontend Service (React + Nginx)
  frontend:
    image: giahuy1412/frontend:v1.0.4 # Thay vì build, sử dụng image đã push
    container_name: fsecurity
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
