name: Deploy Backend & Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Docker Compose
    runs-on: self-hosted  # Chạy trên máy ảo GitHub Actions
    steps:
      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_TOKEN }}"

      - name: run docker-compose
        run: |
          cd /home/ubuntu/ci-cd  # Thư mục chứa docker-compose.yml trên server
          docker compose pull  # Kéo image mới từ Docker Hub
          docker compose up -d --remove-orphans  # Chạy container mới
          docker system prune -f  # Dọn dẹp image cũ (tùy chọn)
          EOF
