name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: copy docker-compose file
        run: |
          sudo cp docker-compose.yml /home/ubuntu/web

      - name: Run Docker Compose
        run: |
          sudo docker-compose -f /home/ubuntu/web/docker-compose.yml down
          sudo docker-compose -f /home/ubuntu/web/docker-compose.yml up -d