name: CI/CD Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_TOKEN }}"

      - name: Pull Latest Image & Restart Services
        run: |
          cd /path/to/ci-cd   # Đổi thành đường dẫn thư mục chứa docker-compose.yml trên server
          docker compose pull
          docker compose up -d --remove-orphans
