name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: copy docker-compose file
        run: |
          sudo cp docker-compose.yml /opt/myapp/

      - name: Run Docker Compose
        run: |
          sudo cd /opt/myapp/
          docker-compose down
          docker-compose up -d